
// --- Creative Director AI Database ---
export const creativeDatabase: Record<string, { scenarios: string[]; interactions: string[] }> = {
    "Studio Foto Profesional": {
        scenarios: [
            "against a seamless white cyclorama background",
            "with a textured gray canvas backdrop",
            "sitting on a vintage Chesterfield sofa",
            "in a minimalist set with geometric props",
            "with dramatic lighting from a single key light",
            "surrounded by an installation of fresh flowers",
            "posing with an antique grand piano",
            "against a raw, industrial brick wall",
            "using a large, ornate golden mirror as a prop",
            "with soft, diffused light from a large window"
        ],
        interactions: [
            "posing for a high-fashion editorial shot",
            "sharing a quiet, intimate moment under soft light",
            "a classic, elegant portrait pose",
            "creating a dramatic silhouette against a bright light",
            "a playful interaction with a simple prop like a chair",
            "a romantic embrace with minimalist background",
            "leaning against each other with confident expressions",
            "a dynamic pose with fabric flowing in the air",
            "a tender forehead kiss captured in close-up",
            "laughing together in a candid studio moment"
        ]
    },
    "Kehidupan Sehari-hari": {
        scenarios: ["on the house terrace with yellow walls", "in the backyard watering plants", "inside a room with vintage vibes", "sitting on a garden chair reading", "in front of the house door with a bicycle", "walking in the park carrying a picnic basket", "preparing breakfast in the kitchen", "folding laundry in the living room", "watering flowers on the balcony", "chatting with neighbors by the fence", "relaxing in the hammock under a tree", "painting on canvas by the window", "feeding fish in a small pond", "sweeping leaves in the yard", "fixing a broken chair together", "arranging flowers in a vase", "repairing a bicycle in the garage", "tidying books on the shelf", "trying on clothes in front of the mirror", "baking bread in the oven", "feeding a pet cat on the porch", "playing guitar on the balcony", "sewing clothes together", "doing yoga in the living room", "watering bonsai plants", "chatting while cooking dinner", "organizing photo albums", "drinking tea in the morning sunshine", "decorating the room with lights", "brushing each other's hair", "feeding birds in the yard", "writing a diary at the table", "arranging potted plants neatly", "cleaning windows together", "folding origami in the room", "playing chess in the yard", "building Lego on the table", "knitting a scarf together", "ironing clothes while laughing", "setting the dining table", "doing karaoke at home", "fixing electronics in the living room", "watering hanging plants", "eating instant noodles in the kitchen", "tidying shoes on the rack", "arranging groceries after shopping", "trying skincare in front of the mirror", "making coffee art together", "repainting the walls", "fixing photo frames on the wall", "di meja makan dengan cahaya pagi masuk dari jendela", "di sofa ruang tamu dengan karpet motif klasik", "di halaman belakang di bawah jemuran bambu", "di teras rumah saat gerimis", "di jendela besar menghadap kebun", "di dapur mungil dengan ubin kotak-kotak", "di ruang kerja kecil dengan rak buku", "di balkon apartemen lantai dua", "di koridor rumah dengan lukisan keluarga", "di tangga kayu dalam rumah"],
        interactions: ["cooking breakfast together while dancing", "sharing headphones to listen to music", "building a puzzle on the coffee table", "planting herbs in small pots", "reading newspapers over morning coffee", "organizing closets and laughing at old clothes", "trying new hairstyles on each other", "making grocery lists while eating snacks", "playing board games competitively", "folding fitted sheets together struggling", "rearranging furniture for better feng shui", "testing paint colors on the wall", "assembling furniture with instruction manual", "sorting through old photographs", "practicing dance moves in living room", "meal prepping for the week ahead", "deep cleaning the house with music", "reorganizing the bookshelf by color", "trying new skincare routines together", "making homemade pizza from scratch", "learning origami from YouTube tutorials", "creating a vision board with magazines", "recording silly videos for social media", "playing charades with inside jokes", "having a spa day at home", "rearranging plants for better sunlight", "practicing calligraphy with brush pens", "making homemade face masks", "playing video games cooperatively", "creating art with watercolors", "organizing digital photos on laptop", "learning new language phrases", "practicing yoga poses together", "making smoothies with fresh fruits", "writing love notes to hide around house", "creating playlists for different moods", "having indoor picnic on living room floor", "doing science experiments in kitchen", "making friendship bracelets", "practicing magic tricks to surprise friends", "creating photo collages for wall", "learning to juggle with soft balls", "making homemade candles with essential oils", "practicing meditation in quiet corner", "creating comics about daily life", "learning to braid hair in new styles", "making homemade soap together", "practicing guitar chords and singing", "creating time capsule for future selves", "making paper airplanes and testing flight"]
    },
    "Kisah Kampus": {
        scenarios: ["in the aesthetic campus hallway with lockers", "on the stairs in front of the faculty building", "at the campus garden picnic area", "in front of the classroom door waiting", "in the library between tall bookshelves", "walking home from campus with backpacks", "sitting under a large tree with laptops", "drinking coffee in the campus canteen", "waiting at the bus stop with friends", "taking photos near the faculty monument", "standing in front of the student notice board", "buying books in the campus bookstore", "resting on a bench under shady tree", "walking through the main campus gate", "chatting near the campus fountain", "eating snacks by the cafeteria windows", "sitting together in the computer lab", "discussing in front of the projector screen", "standing by the bicycle parking lot", "playing guitar in the student lounge"],
        interactions: ["walking while laughing and carrying laptops", "sitting and chatting on the concrete stairs", "having picnic on grass with homemade snacks", "standing in line waiting for class to begin", "searching for reference books together", "sharing earphones while listening to music", "drinking coffee while laughing at jokes", "helping carry each other's heavy books", "adjusting tie or scarf affectionately", "posing for mandatory class group photos", "eating instant noodles together at canteen", "copying lecture notes from each other", "sharing laptop to watch funny videos", "giving snacks to each other during break", "playing guitar while partner sings along", "posing with exaggerated funny gestures", "drinking bottled water while studying", "helping write and edit assignments", "sharing umbrellas when raining heavily", "posing while holding thick textbooks"]
    },
     "Pedesaan": {
        scenarios: ["on the terrace of a wooden village house", "at the bamboo hut near the rice field", "in front of a small village grocery shop", "sitting at the roadside wooden bench", "walking on a narrow dirt path between houses", "resting at the bamboo gazebo in garden", "feeding goats near the traditional barn", "carrying water buckets from the village well", "waiting at the bus stop bamboo shelter", "playing marbles on the dusty ground"],
        interactions: ["peeling fresh corn kernels on woven mat together", "sitting on hut steps pointing at passing clouds", "feeding chickens with rice grains together", "pretending to be shopkeepers at grocery store", "flying colorful kites in the open field", "pushing a vintage motorbike that broke down", "drinking hot tea and eating plain biscuits", "laughing while peeling cassava with knife", "fixing broken bamboo fence side by side", "eating hot fried bananas straight from oil"]
    },
    "Hutan Tropis": {
        scenarios: ["in front of a majestic cascading waterfall", "on a hanging rope bridge among trees", "at the crystal clear riverbank", "under a giant ancient banyan tree", "walking on the narrow forest trail", "sitting on moss-covered rocks", "near a small traditional jungle hut", "resting on a bamboo raft", "in front of mysterious hidden cave entrance", "at the cliff edge overlooking green valley"],
        interactions: ["feeling refreshing waterfall splash on skin", "holding hands while crossing scary bridge", "sitting on big smooth rock by river", "leaning on tree trunk while reading book", "walking hand in hand along jungle path", "laughing while getting soaked from rain", "hugging under massive banyan tree roots", "eating fresh tropical fruits by riverbank", "drinking crystal water from bamboo cup", "sharing binoculars to spot rare birds"]
    },
    "Street Food": {
        scenarios: ["in front of a steaming bakso cart", "sitting at a busy pecel lele tent", "by the colorful ice pops seller", "at the crowded night market food stall", "standing near aromatic satay grill", "posing by fried noodle hawker", "waiting at popular martabak stall", "eating at nasi goreng cart", "choosing snacks at bustling pasar malam", "standing near sweet corn seller"],
        interactions: ["feeding each other hot bakso meatballs", "eating under colorful neon lights", "sharing ice pops on hot day", "choosing food together excitedly", "fanning satay smoke away laughing", "laughing while eating spicy noodles", "sharing crispy martabak slice", "hugging while eating fried rice", "posing while holding pink cotton candy", "eating grilled corn together messily"]
    },
    "Tokyo": {
        scenarios: ["at busy Shibuya Crossing with crowds", "in narrow Shinjuku Omoide Yokocho alley", "at traditional Senso-ji Temple Asakusa", "at a minimalist cafe in trendy Daikanyama", "at colorful Akihabara electronics district", "in peaceful Shinjuku Gyoen Park", "at modern Tokyo International Forum", "posing by iconic Tokyo Tower", "at serene Meiji Shrine forest path", "at vibrant Harajuku Takeshita Street"],
        interactions: ["using transparent umbrella in rain", "eating steaming ramen together", "staring in wonder with paper lanterns background", "drinking coffee at minimalist cafe", "laughing at funny gacha machine toys", "having romantic picnic on grass", "admiring sleek modern architecture together", "posing while taking purikura photo booth", "hugging while feeding pigeons", "posing while holding shopping bags"]
    },
    "Kyoto": {
        scenarios: ["at Arashiyama Bamboo Grove", "at Nara Park feeding deer", "walking in Gion district", "inside a traditional tea house", "at Fushimi Inari Shrine torii gates", "on Togetsukyo Bridge", "on a boat at Hozugawa River", "at Kiyomizu-dera temple balcony", "walking through Philosopher’s Path", "posing near Yasaka Pagoda"],
        interactions: ["whispering to each other", "feeding deer together", "walking while wearing kimono", "joining a tea ceremony", "running through torii gates", "leaning on bridge railing", "rowing boat together", "pointing at temple view", "walking hand in hand on path", "posing with pagoda in background"]
    },
    "Hokkaido": {
        scenarios: ["in Furano lavender fields", "in Sapporo snow festival", "on Mount Hakodate peak", "walking along Otaru Canal", "posing at Blue Pond Biei", "visiting a local dairy farm", "skiing in Niseko slopes", "posing at Asahiyama Zoo", "posing in Sapporo beer museum", "posing at Shikisai-no-Oka flower field"],
        interactions: ["hugging warmly in snow", "throwing snowballs playfully", "admiring night city view", "walking by canal with lanterns", "posing with surreal blue pond", "feeding cows together", "skiing hand in hand", "posing with polar bear statue", "cheering with beer mugs", "hugging in flower fields"]
    },
    "Osaka": {
        scenarios: ["at Dotonbori Glico Man sign", "walking through Kuromon Ichiba Market", "posing at Osaka Castle garden", "in Shinsekai under Tsutenkaku Tower", "walking Hozenji Yokocho lantern alley", "at Osaka Aquarium Kaiyukan", "posing at Umeda Sky Building observatory", "shopping in Shinsaibashi arcade", "posing in Namba Yasaka Shrine", "walking around Sumiyoshi Taisha Shrine"],
        interactions: ["mimicking the Glico Man pose", "sharing takoyaki together", "posing romantically with castle in background", "playing arcade games in Shinsekai", "walking under lanterns", "pointing at aquarium fish", "hugging at observatory deck", "shopping together holding bags", "posing under shrine lion head", "walking hand in hand in shrine path"]
    },
    "Bali": {
        scenarios: ["in Tegallalang rice terraces", "on Kelingking Beach cliff", "at Ulun Danu Beratan Temple", "at Canggu beach club", "in front of Handara Gate", "on swing above rice field", "posing at Tanah Lot Temple", "on Uluwatu cliffside", "at Seminyak beach during sunset", "walking around Ubud Art Market"],
        interactions: ["wearing farmer’s hat together", "hugging with blue ocean behind", "posing with temple reflection", "relaxing on daybed with coconut drinks", "posing framed by temple gate", "swinging together above rice fields", "posing at sunset temple", "hugging on cliff edge", "walking barefoot on beach sand", "shopping and bargaining at market"]
    },
    "Yogyakarta": {
        scenarios: ["at Taman Sari Water Castle ruins", "walking along Malioboro Street at night", "posing at Prambanan Temple complex", "in Mangunan Pine Forest", "at Gumuk Pasir sand dunes", "sitting at an angkringan stall", "posing near Borobudur Temple sunrise", "walking in Kotagede silver district", "posing at Ullen Sentalu Museum", "posing near Plaosan Temple"],
        interactions: ["exploring ancient castle corridors together", "riding becak together romantically", "posing with temple silhouette at sunset", "walking between tall pine trees", "running on sand dunes playfully", "sitting cross-legged at angkringan food stall", "watching sunrise at Borobudur temple", "shopping silver jewelry together", "reading art captions together", "posing among ancient twin temples"]
    },
    "Jakarta": {
        scenarios: ["in historic Kota Tua colonial square", "inside modern MRT station", "on rooftop bar with skyscraper view", "at Museum MACAN contemporary art gallery", "at trendy Senopati coffee shop", "on JPO Phinisi pedestrian bridge", "posing in National Monument park", "posing at Ancol beach recreational area", "posing at Taman Mini Indonesia Indah", "posing near grand Istiqlal Mosque"],
        interactions: ["posing with colorful vintage bicycles", "leaning on sleek glass MRT wall", "cheering drinks under sparkling skyline", "posing with modern art installation", "chatting on comfortable sofa café", "walking on illuminated bridge at night", "posing with towering Monas background", "walking barefoot on beach sand", "posing in traditional cultural pavilion", "posing at grand mosque gate"]
    },
    "Paris": {
        scenarios: ["at the Eiffel Tower from Trocadéro square", "under the Eiffel Tower at night", "on Pont Alexandre III bridge", "in front of the Louvre glass pyramid", "inside Musée d’Orsay clock window", "on the steps of Sacré-Cœur Basilica", "at Montmartre artist square", "walking along the Seine River", "picnic at Champ de Mars park", "at Shakespeare & Company bookstore"],
        interactions: ["kissing with Eiffel Tower view", "posing hand-in-hand under tower lights", "hugging on ornate bridge", "posing artistically at Louvre", "looking out giant clock window", "sitting on basilica steps", "sketching portraits together", "holding hands along the river", "lying on picnic blanket", "reading poetry together"]
    },
    "Santorini": {
        scenarios: ["on a blue dome rooftop in Oia", "watching sunset in Oia cliffs", "walking in narrow white alleys", "posing in front of windmill", "at Amoudi Bay fishing port", "sitting on white stairs with flowers", "posing at Imerovigli viewpoint", "posing near Red Beach cliffs", "posing at Akrotiri lighthouse", "posing in Pyrgos village streets"],
        interactions: ["holding hands on blue dome rooftop", "hugging during sunset", "laughing in white alleyways", "posing with windmill background", "sharing seafood at port", "sitting close on stairs", "hugging at scenic viewpoint", "posing near volcanic cliffs", "hugging near lighthouse", "walking hand-in-hand in village"]
    },
    "Rome": {
        scenarios: ["throwing coins at Trevi Fountain", "posing in front of the Colosseum", "eating gelato at Spanish Steps", "walking on cobblestone streets of Trastevere", "at Piazza Navona fountains", "in front of Pantheon entrance", "posing in Vatican St. Peter’s Square", "inside Vatican Museums hall", "walking along Tiber River", "on Castel Sant’Angelo bridge"],
        interactions: ["throwing coins together with eyes closed", "hugging with Colosseum in background", "sharing a gelato cone", "walking hand-in-hand in Trastevere", "posing near fountains while laughing", "hugging under Pantheon columns", "posing romantically in Vatican square", "admiring Renaissance frescoes", "walking by the river hand-in-hand", "hugging on historic bridge"]
    },
    "Seoul": {
        scenarios: ["wearing hanbok at Gyeongbokgung Palace", "posing at N Seoul Tower with love locks", "walking in Myeongdong shopping street", "posing in themed café in Hongdae", "posing at Bukchon Hanok Village", "posing in Dongdaemun Design Plaza", "posing at Cheonggyecheon Stream", "posing in Itaewon streets", "posing at Gwangjang Market", "posing at Changdeokgung Secret Garden"],
        interactions: ["posing in colorful hanbok", "hanging love lock together", "shopping for cosmetics", "taking selfie in themed café", "walking in traditional alley", "posing under LED lights", "hugging near urban stream", "posing with nightlife backdrop", "eating Korean street food", "hugging in hidden garden"]
    },
    "New Zealand": {
        scenarios: ["by Lake Wakatipu in Queenstown", "in a lupin flower field in Lake Tekapo", "with The Remarkables mountain range", "at Hobbiton Movie Set", "walking in Fiordland National Park", "on Milford Sound cruise", "at Franz Josef Glacier viewpoint", "posing at Mount Cook base", "on Lake Pukaki turquoise shore", "in Rotorua geothermal park"],
        interactions: ["sitting on pier enjoying mountain view", "running through purple lupin fields", "posing adventurously with snowy peaks", "posing by Hobbit door", "hugging under rainforest trees", "pointing at waterfalls", "posing with ice background", "hugging near snowy base", "posing with turquoise water", "taking selfie with geyser steam"]
    },
    "Thailand": {
        scenarios: ["at Bangkok floating markets", "in Chiang Mai temple complex", "on Phi Phi Island boats", "at Ayutthaya ancient ruins", "in Phuket beach paradise", "on Krabi limestone cliffs", "at Sukhothai historical park", "in Koh Samui coconut groves", "on Railay Beach rock climbing", "at Erawan Falls emerald pools"],
        interactions: ["bargaining floating market vendors", "praying temple golden Buddha", "island hopping longtail boats", "exploring ancient Siamese capital", "relaxing pristine white sand", "rock climbing limestone karsts", "cycling UNESCO heritage site", "picking fresh coconuts", "learning rock climbing techniques", "swimming seven-tier waterfall"]
    },
    "Maldives": {
        scenarios: ["on overwater villa deck", "in crystal lagoon snorkeling", "at sunset dolphin cruise", "on private sandbank picnic", "in underwater restaurant dining", "at coral reef diving site", "on seaplane scenic flight", "in spa overwater treatment", "at local fishing village", "on yacht sailing trip"],
        interactions: ["relaxing on overwater deck", "swimming in crystal waters", "spotting dolphins together", "dining on private sandbank", "eating surrounded by fish", "diving colorful coral reef", "viewing atolls from above", "enjoying couples spa treatment", "learning local island life", "sailing turquoise waters"]
    },
    "Australia": {
        scenarios: ["at Sydney Opera House sails", "on Sydney Harbour Bridge climb", "at Bondi Beach surf culture", "in Blue Mountains eucalyptus", "at Uluru sacred monolith", "on Great Ocean Road drive", "in Melbourne laneways art", "at Cairns Great Barrier Reef", "on Fraser Island sand dunes", "in Tasmania Devil Island"],
        interactions: ["posing under iconic sails", "climbing bridge together", "learning surf techniques", "hiking misty mountains", "watching Uluru sunrise", "driving coastal cliffs", "exploring street art", "snorkeling coral reef", "sandboarding giant dunes", "spotting Tasmanian devils"]
    },
    "Morocco": {
        scenarios: ["in colorful Marrakech souks", "at Bahia Palace gardens", "near Koutobia Mosque minaret", "in Majorelle Garden blue villa", "at Jemaa el-Fnaa square sunset", "in traditional riad courtyard", "at Atlas Mountains viewpoint", "walking in Chefchaouen blue streets", "at Sahara desert camp", "on camel trek at sunset"],
        interactions: ["bargaining in spice markets together", "sharing mint tea in riad", "riding camels at sunset", "getting henna tattoos together", "learning to cook tagine", "shopping for carpets and lanterns", "watching snake charmers", "listening to Gnawa music", "exploring labyrinthine medina", "climbing minaret stairs"]
    },
    "Iceland": {
        scenarios: ["at Seljalandsfoss waterfall", "in Blue Lagoon geothermal spa", "at Northern Lights viewing", "on Diamond Beach black sand", "at Geyser Strokkur eruption", "in Thingvellir National Park", "at Gullfoss golden falls", "on Reynisfjara black beach", "at Skaftafell ice caves", "in Westman Islands puffins"],
        interactions: ["soaking in geothermal pools", "chasing Northern Lights together", "walking behind waterfall curtain", "collecting black sand diamonds", "warming hands at geyser steam", "exploring continental drift valley", "feeling waterfall mist spray", "building cairns on beach", "crawling through ice caves", "spotting puffins on cliffs"]
    },
    "Norway": {
        scenarios: ["at Geirangerfjord waterfall", "in Lofoten dramatic peaks", "watching Northern Lights in Tromso", "on Preikestolen cliff edge", "in Bergen colorful houses", "at Flam railway scenic route", "on Atlantic Road bridges", "in Alesund Art Nouveau town", "at Nærøyfjord cruise", "in Stavanger old town"],
        interactions: ["hugging under Aurora Borealis", "posing on fjord cruise deck", "hiking dramatic mountain trails", "standing on cliff edge bravely", "walking colorful harbor streets", "riding scenic mountain railway", "posing on curved bridge", "exploring Art Nouveau architecture", "kayaking narrow fjord waters", "wandering cobblestone streets"]
    },
    "Switzerland": {
        scenarios: ["at Matterhorn pyramid peak", "on Jungfraujoch top of Europe", "in Zermatt car-free village", "at Rhine Falls powerful cascade", "in Lucerne Chapel Bridge", "on Lake Geneva vineyard slopes", "in Grindelwald alpine valley", "at Château de Chillon castle", "in Interlaken adventure hub", "on Mount Titlis revolving cable car"],
        interactions: ["posing with iconic mountain pyramid", "standing on Europe's highest station", "walking electric taxi streets", "feeling waterfall mist spray", "crossing historic wooden bridge", "wine tasting with lake view", "hiking First cliff walk", "exploring medieval castle", "paragliding over twin lakes", "rotating 360 degrees slowly"]
    }
};

export const photographicStyles = ["environmental portrait shot from a distance", "dynamic wide shot capturing movement and the surrounding area", "a candid stolen moment captured from afar", "a shallow depth-of-field portrait with dreamy bokeh", "a shot framed creatively through objects like leaves or windows", "a playful action shot full of energy and laughter", "a romantic silhouette against sunset or city lights", "a perfectly symmetrical Wes Anderson-style composition", "a wide establishing shot showing the full environment", "an intimate close-up focusing on expressions and hands", "a natural documentary style capturing authentic moments", "a dramatic overhead shot from above", "a through-the-lens perspective with creative framing", "a golden ratio balanced composition", "a minimalist portrait with lots of negative space", "a layered composition with foreground and background depth", "a slow shutter motion blur emphasizing energy", "a high-contrast black and white shot", "a soft dreamy-focus portrait with romance", "a reflection shot using water or glass surfaces", "a symmetrical composition with architecture", "a candid street-style photograph", "a fine art portrait with gallery aesthetics", "a vintage film look with warm grading", "a modern editorial style shot", "a cinematic wide shot like a movie scene", "a golden hour glow emphasizing warmth", "a night city shot with neon reflections", "a high-fashion editorial portrait", "a rustic outdoor shoot with film texture", "a fisheye wide shot for creative distortion", "a bird’s-eye drone capture with dramatic scale", "a worm’s-eye low-angle shot emphasizing grandeur", "a Dutch tilt cinematic angle for tension", "a long exposure light-trail capture at night", "a dreamy pastel-toned soft-focus portrait", "a vintage film grain look", "a moody cinematic portrait with dark shadows", "a surreal double exposure style image", "a wide-angle lens shot emphasizing perspective", "a candid laughter shot mid-action", "an elegant black-and-white high contrast frame", "a soft-focus veil-framed kiss", "a prism refraction rainbow flare portrait", "an underwater dreamy shot", "a silhouette with fireworks behind", "a pastel matte color grade", "a bold high-saturation vivid look", "a stormy moody tone", "a candle-lit close-up", "a dramatic sunflare portrait", "a clean editorial magazine shot", "an HDR dreamy surreal shot", "a minimalist top-down portrait", "a cozy indoor lamp-lit portrait", "a creative mirror-frame shot", "a vintage sepia tone shot", "a Polaroid nostalgic capture"];
export const emotionalCues = ["a quiet moment of shared understanding", "a playful glance while teasing each other", "a look of serene contentment", "a soft laugh over a private joke", "a warm silence with no need for words", "a subtle, knowing smile", "a gaze filled with admiration", "eyes sparkling with joy and laughter", "a tender moment of intimacy", "a spontaneous burst of laughter", "gentle eyes radiating devotion", "a peaceful expression of trust", "a mischievous grin at an inside joke", "a vulnerable emotional connection", "a confident look of deep partnership", "a soft expression of gratitude", "a dreamy look of anticipation", "a warm smile of belonging", "an excited expression of adventure", "a calm serenity of feeling understood", "a gentle surprise at a sweet gesture", "a content sigh of happiness", "a knowing look that says everything", "a bashful smile of new love", "a steady gaze of commitment", "a radiant joy of celebration", "a joyful scream mid-play", "a tearful moment of joy", "a playful wink full of charm", "a proud smile for each other", "a bashful laugh while blushing", "a romantic nose-to-nose eskimo kiss", "a burst of laughter while dancing", "a peaceful forehead touch", "a bittersweet yet warm gaze", "a glowing proud smile", "a shy glance followed by giggles", "a heartfelt look across the room", "an emotional embrace", "a calming breath in comfort", "an intense eye-lock of passion", "a dreamy romantic sigh", "a surprised laugh mid-movement", "a joyful cheer together", "a wide-eyed wonder", "a soft giggle while hiding", "a proud smile at success", "a warm glow of gratitude", "a playful mischievous grin"];
export const maleDirectionCues = ["the man looks confidently into the camera with a warm smile", "the man laughs wholeheartedly while glancing off-frame", "the man gazes at his partner with admiration", "the man smiles at the camera while holding his partner close", "the man looks thoughtfully into the distance as his partner admires him", "the man interacts with a nearby object, like touching leaves or holding a cup of coffee", "the man adjusts his sleeve while glancing at his partner lovingly", "the man runs his hand through his hair with a confident smile", "the man looks down at his hands thoughtfully", "the man gazes at the horizon with a protective stance", "the man laughs heartily while pointing at something funny", "the man gently touches a wall while looking back", "the man checks his watch casually", "the man straightens his collar with quiet confidence", "the man looks up at the sky with wonder", "the man rests his chin on his hand in thought", "the man gestures animatedly while telling a story", "the man looks over his shoulder with a charming smile", "the man adjusts his jacket elegantly", "the man touches his partner’s hand reassuringly", "the man looks down shyly with a smile", "the man stretches comfortably", "the man examines something nearby with curiosity", "the man balances playfully on one foot", "the man gently adjusts his partner’s hair", "the man shares a laugh while looking sideways", "the man stands with hands in pockets", "the man leans against a wall casually", "the man tilts his head curiously with warmth", "the man closes his eyes smiling softly", "the man whispers playfully to his partner", "the man rests his chin gently on his partner’s shoulder", "the man gestures toward something in excitement", "the man tilts slightly with an affectionate smile"];
export const femaleDirectionCues = ["the woman smiles softly while tucking her hair", "the woman gazes lovingly at her partner", "the woman laughs with eyes closed, head tilted back", "the woman looks down shyly while holding hands", "the woman walks ahead, glancing back playfully", "the woman holds a bouquet close to her chest", "the woman brushes her partner’s cheek gently", "the woman twirls gracefully in her dress", "the woman leans on her partner peacefully", "the woman closes her eyes to savor the moment", "the woman laughs while covering her mouth", "the woman adjusts her partner’s tie affectionately", "the woman rests her head on her partner’s chest", "the woman looks out the window dreamily", "the woman lifts her dress slightly while walking", "the woman playfully hides behind her partner", "the woman rests her chin on her partner’s shoulder", "the woman whispers sweetly into her partner’s ear", "the woman touches her hair while glancing sideways", "the woman reaches out her hand for her partner", "the woman kneels to adjust her partner’s outfit", "the woman tilts her head with a tender smile", "the woman shields her eyes from the sun", "the woman bites her lip gently while looking", "the woman spreads her arms as if embracing the world", "the woman rests against a wall looking away", "the woman spins while laughing joyfully", "the woman leans casually against her partner", "the woman gazes with admiration softly", "the woman touches her necklace thoughtfully"];
export const coupleInteractionCues = ["the couple laughs while walking hand-in-hand", "the couple dances barefoot in the grass", "the couple runs playfully through a field", "the couple shares an ice cream together", "the couple hugs under one umbrella", "the couple kisses on the forehead", "the couple walks side by side at sunset", "the couple laughs together on stairs", "the couple clinks glasses during a toast", "the couple spins each other around playfully", "the couple shares headphones listening to music", "the couple kisses on the cheek with joy", "the couple balances playfully on a log", "the couple playfully chases each other", "the couple holds hands across a café table", "the couple leans against each other reading a book", "the couple sits cross-legged on a picnic blanket", "the couple shares a warm blanket", "the couple high-fives with excitement", "the couple laughs while taking a selfie", "the couple walks with arms wrapped", "the couple kisses in the rain", "the couple shares cotton candy", "the couple whispers secrets close", "the couple holds each other eyes closed", "the couple runs into the ocean together", "the couple watches fireworks hand in hand", "the couple laughs over spilled coffee", "the couple playfully argues over food", "the couple leans in nose-to-nose smiling"];
export const positionCues = ["the woman stands to the left", "the man stands slightly behind looking over her shoulder", "they stand face-to-face, eyes locked", "the woman stands slightly in front", "they walk side-by-side brushing hands", "they sit together closely", "the man lifts the woman playfully", "they lie on grass gazing at the sky", "the woman rests her head on his shoulder", "they stand back-to-back holding hands", "they sit on steps at different heights", "the man kneels as the woman touches his face", "they walk hand in hand symmetrically", "they dance freely in an open space", "the woman twirls gracefully", "they sit cross-legged facing each other", "the man carries the woman piggyback", "she leans against his chest", "they sit on a fountain edge", "they stand framed by an archway", "they recline together on a blanket", "he rests his arm protectively", "they stand diagonally apart with long gaze", "she reaches forward as he guides", "they hold hands around a wall corner", "they walk barefoot along the shore", "they share a chair closely", "she sits sideways on his lap", "they stand under a tree interlocked", "he holds her waist gently from behind"];
export const lightingMoodCues = ["golden hour light casting a glow", "soft candlelight illuminating faces", "moody shadows through blinds", "fairy lights in the background", "sunset glow through trees", "morning sunlight filling room", "city neon cinematic vibe", "soft light through curtains", "silhouettes against skyline", "moonlight illuminating softly", "lantern light in the dark", "fireplace glow casting shadows", "streetlights on cobblestones", "festive string lights", "rainbow prism reflections", "starlight in background", "dramatic spotlight highlight", "soft foggy morning light", "car headlights in rain", "underwater shimmering glow", "sparklers at night", "warm backlight through leaves", "festival lights framing", "storm clouds backdrop", "golden reflections in puddles"];
export const propEnvironmentCues = ["holding coffee cups together", "posing with vintage bicycles", "writing notes on fogged window", "sharing popcorn at cinema", "reading books side by side", "posing with balloons in park", "sitting on vintage car hood", "playing guitar outdoors", "sharing headphones under blanket", "walking dogs together", "holding sparklers at night", "blowing soap bubbles", "posing with picnic basket", "posing with surfboards", "painting together in studio", "posing with polaroid photos", "posing with old suitcases", "riding a carousel horse", "posing with wildflowers bouquet", "sharing cotton candy", "holding ice cream cones", "posing with skateboards", "taking photos with vintage camera", "reading a travel map", "sitting on swings side by side"];
export const storyScenes = ["morning preparation with bride adjusting veil in vintage mirror", "playful kitchen breakfast scene with coffee and pastries", "farewell moment at a train station with vintage suitcases", "secret garden proposal recreation with hidden ring", "childhood sweetheart reunion at old school playground", "romantic picnic setup with handwritten love letters", "surprise birthday celebration with intimate candlelit cake", "lazy Sunday morning reading newspapers in bed", "cooking together while dancing to vintage music", "stargazing on rooftop with telescope and blankets", "building sandcastles together at golden hour beach", "vintage car road trip with maps and snacks", "antique bookstore browsing with coffee in hand", "farmers market shopping with fresh flowers and produce", "art gallery opening with champagne and paintings", "cozy cabin retreat with fireplace and board games", "brewery tasting with craft beer flights and laughter", "midnight diner scene with comfort food and conversation", "flower crown making workshop in blooming garden", "pottery class with clay-covered hands and aprons", "wine vineyard harvest with grape baskets and sun hats", "lighthouse keeper's cottage with nautical elements", "abandoned carnival with vintage rides and cotton candy", "library study session with stacks of books and notes", "music studio recording session with instruments and headphones", "bakery early morning with fresh bread and flour dusted aprons", "greenhouse plant care with watering cans and seedlings", "vintage camera shop with film rolls and antique equipment", "rooftop garden party with string lights and herbs"];
export const cameraTechniques = ["35mm film grain with warm color temperature", "anamorphic lens flare with cinematic aspect ratio", "tilt-shift photography creating miniature effect", "double exposure blending couple with landscape", "bokeh circles from vintage lens at golden hour", "fish-eye lens creating dreamy distortion", "macro lens capturing intimate hand details", "long exposure with motion blur background", "overhead drone shot with geometric patterns", "through-the-glass reflection technique", "silhouette against backlit window", "split-diopter creating dual focus planes", "vintage polaroid instant film aesthetic", "medium format film with square composition", "infrared photography with ethereal glow", "cross-processing for vintage color shift", "grain structure mimicking Kodak Portra 400", "shallow depth of field with creamy background", "Dutch angle for dynamic composition", "bird's eye view from elevated position", "worm's eye view from ground level", "prism photography creating rainbow effects", "multiple exposure creating ghostly overlays", "vintage viewfinder frame overlay", "film burn effects on image edges", "light leak streaks across the frame", "chromatic aberration for dreamy quality", "vignetting effect darkening the corners", "cross-star filter creating sparkle effects"];
export const culturalThemes = ["traditional Japanese hanbok with cherry blossoms", "Balinese ceremonial attire with temple backdrop", "Scottish highlands with tartan and bagpipes", "Italian countryside with olive groves and vineyards", "French château with vintage champagne and roses", "Indian palace with intricate henna and saris", "Mexican hacienda with colorful papel picado", "English garden party with tea service and florals", "Korean traditional hanbok in bamboo forest", "Greek island with whitewashed buildings and blue domes", "Moroccan riad with ornate tiles and lanterns", "Spanish flamenco with red roses and castanets", "Chinese tea ceremony with silk qipao", "Thai temple with golden Buddha and lotus flowers", "Russian winter wonderland with fur and troika", "Irish countryside with Celtic knots and clovers", "Brazilian carnival with feathers and sequins", "Egyptian desert with ancient pyramids backdrop", "Norwegian fjords with traditional bunads", "Turkish bazaar with colorful carpets and lamps", "Peruvian mountains with alpaca wool textiles", "African safari with traditional tribal jewelry", "Australian outback with eucalyptus and kangaroos", "Canadian maple forest with plaid and autumn leaves", "Caribbean beach with tropical flowers and steel drums", "German Oktoberfest with traditional dirndl and lederhosen", "Dutch tulip fields with wooden shoes and windmills", "Swedish midsummer with flower crowns and maypoles", "Polish highland with folk embroidery and wooden architecture"];
export const emotionBoosters = ["explosive laughter with tears of joy", "passionate embrace with intense eye contact", "playful food fight with flour and giggles", "dramatic dip dance move with flowing dress", "surprise proposal shock and overwhelming happiness", "competitive game with playful rivalry and teasing", "nostalgic reminiscing with bittersweet smiles", "adventurous adrenaline rush from heights or speed", "tender vulnerability with gentle whispered secrets", "celebration victory with champagne and cheers", "mischievous pranking with guilty grins", "romantic serenading with heartfelt song", "protective instinct with fierce devotion", "childlike wonder discovering something magical", "passionate argument followed by makeup kiss", "grateful tears for unexpected surprise", "confident swagger walking hand in hand", "shy bashfulness with hidden smiles", "wild abandonment dancing in the rain", "proud accomplishment sharing dreams achieved", "gentle teasing with affectionate mockery", "breathless anticipation before big reveal", "overwhelming gratitude for life's blessings", "fierce loyalty defending each other", "spontaneous adventure with reckless abandon", "peaceful contentment in perfect silence", "electric chemistry with magnetic attraction", "brave courage facing fears together", "pure bliss in simple moment of connection"];
export const groupInteractions = ["bridesmaids helping adjust wedding dress train", "groomsmen fixing boutonniere with careful precision", "flower girls scattering petals while giggling", "parents offering emotional blessing and tight hugs", "siblings sharing inside jokes and childhood memories", "grandparents giving wisdom and ancestral jewelry", "best friends group hug with tears and laughter", "wedding party toast with champagne glasses raised", "children playing hide and seek around couple", "family dog wearing bow tie joining portrait", "musicians serenading with acoustic guitar and violin", "wedding planner coordinating group with clipboard", "photographer directing large family arrangement", "officiant practicing ceremony with wedding party", "caterers serving appetizers during cocktail hour", "elderly relatives sharing stories on garden bench", "teenage cousins taking selfies with couple", "ring bearer practicing careful steps down aisle", "makeup artist touching up bride with bridesmaids watching", "florist arranging bouquets with wedding party", "extended family recreating old photo poses", "college friends surprising couple with flashmob dance", "work colleagues presenting group gift", "neighbors joining impromptu street celebration", "childhood friends sharing embarrassing stories", "sports team members recreating victory celebration", "hobby group incorporating shared interest props", "travel companions sharing destination photo memories", "volunteer group from shared charity work"];
export const postProcessingFilters = ["warm film emulation with golden highlights", "cool blue shadows with warm skin tones", "vintage sepia with subtle grain texture", "high contrast black and white with deep shadows", "soft pastel colors with dreamy highlights", "matte finish with lifted blacks", "cinematic color grading with teal and orange", "faded film look with desaturated colors", "cross-processed slides with color shifts", "infrared effect with glowing skin tones", "selective color with monochrome background", "HDR tone mapping with enhanced details", "vintage polaroid with white borders", "film burn with light leak streaks", "lomography with heavy vignetting", "kodachrome saturation with rich reds", "fujifilm simulation with green undertones", "agfa color rendering with unique palette", "ilford black and white with fine grain", "tri-x pushed processing with high contrast", "portra 400 skin tone reproduction", "velvia landscape saturation boost", "provia natural color accuracy", "ektar vivid color enhancement", "gold reflector warmth simulation", "silver reflector cool tone balance", "diffused natural light softening", "golden hour color temperature shift", "blue hour moody atmosphere enhancement"];
export const motionActivities = ["spinning together with dress flowing in wind", "running hand in hand through flower field", "jumping simultaneously with arms raised high", "dancing bachata with hip movements and turns", "twirling bride with veil creating circular motion", "walking away from camera with confident stride", "skipping playfully down cobblestone street", "climbing rocks together with helping hands", "swinging on rope swing over water", "riding tandem bicycle through countryside", "playing frisbee with athletic catches", "building snowman with winter clothing", "splashing in shallow water with bare feet", "throwing confetti with celebratory gestures", "doing cartwheel race across grassy field", "piggyback ride with joyful expressions", "tossing bouquet with triumphant catch", "balancing on fallen log over stream", "hiking uphill with walking sticks", "kayaking together with synchronized paddling", "rock skipping competition at lake shore", "playing catch with vintage baseball", "doing yoga poses together on beach", "ice skating with linked arms", "horseback riding through forest trail", "surfing waves with shared surfboard", "zip-lining with fearless adventure", "bungee jumping with trust fall", "parasailing with panoramic views"];
export const dynamicPoses = ["sitting side by side on steps with woman leaning on man's shoulder", "walking hand in hand with woman slightly ahead, looking back", "man carrying woman piggyback style while both laugh", "lying on grass looking up at sky with heads touching", "dancing with woman spinning under man's raised arm", "sitting on bench with woman's legs across man's lap", "standing back to back holding hands with heads turned toward each other", "woman sitting on ledge with man standing between her knees", "both running toward camera with arms outstretched", "man dipping woman in dramatic dance pose", "sitting cross-legged facing each other with foreheads touching", "walking away from camera with arms around each other's waist", "woman jumping into man's arms in mid-air", "sitting on ground with woman between man's legs, both facing forward", "standing with woman behind man, arms wrapped around his chest", "lying side by side on stomachs, propped on elbows facing each other", "man kneeling with woman sitting on his knee", "both sitting on swing with woman sideways across man's lap", "standing profile to camera in intimate conversation", "woman sitting on man's shoulders celebrating victory pose", "lying in opposite directions with heads on each other's stomachs", "man lifting woman by waist as she spreads arms like flying", "sitting on stairs at different heights creating dynamic levels", "woman leaning against wall while man faces her with hands on wall", "both crouching down examining something on ground together", "woman sitting backwards on chair while man leans over her shoulder", "both lying on their sides facing each other in conversation", "man spinning woman in circle with her dress flowing", "woman climbing on man's back playfully", "both sitting on edge of fountain trailing fingers in water"];
export const creativeAngles = ["shot from above showing couple lying on ground in heart shape", "low angle shot making couple look heroic against sky", "through doorway or window frame creating natural border", "reflection shot using water puddle or mirror surface", "between tree branches creating natural frame", "from behind flower bushes for romantic peek-a-boo effect", "wide shot showing couple small in vast landscape", "close-up on intertwined hands with faces softly blurred", "over-the-shoulder shot of one looking at the other", "silhouette against bright background like sunset", "from ground level showing couple against towering architecture", "through crowd focusing on couple in their own world", "bird's eye view from balcony or elevated position", "using leading lines like path or fence toward couple", "split-level composition with couple on different planes", "extreme close-up of faces almost touching", "worm's eye view emphasizing height and drama", "through glass or water creating dreamy distortion", "diagonal composition with dynamic energy", "macro focus on small details with couple softly in background"];
export const emotionalExpressions = ["uncontrollable laughter with eyes squeezed shut", "tender moment with soft whispered conversation", "surprised joy with wide eyes and open mouths", "peaceful contentment with gentle closed-eye smiles", "playful mischief with secretive grins", "overwhelming emotion with tears of happiness", "confident pride walking with heads held high", "shy bashfulness with hidden giggles behind hands", "intense romantic gaze locked in eye contact", "carefree abandon with arms spread wide", "conspiratorial whispers with heads close together", "celebratory cheering with fists pumped in air", "gentle teasing with playful pushed-out tongues", "dreamy contentment looking off into distance", "energetic excitement jumping up and down"];
export const actionInteractions = ["feeding each other strawberries or ice cream", "building something together like sandcastle or snowman", "teaching each other dance moves with patient instruction", "taking selfies with exaggerated funny faces", "playing rock-paper-scissors with competitive intensity", "sharing umbrella in rain with shoulders touching", "high-fiving after accomplishing something together", "painting each other's faces with playful concentration", "racing each other with determined expressions", "solving puzzle or riddle with heads bent together", "making wishes while blowing dandelion seeds", "star-gazing while pointing at constellations", "skipping stones across water with focused technique", "preparing picnic spread with coordinated teamwork", "flying kite together with hands on same string", "blowing bubbles and trying to catch them", "playing tug-of-war with playful determination", "braiding each other's hair with gentle care", "juggling objects together in synchronized motion", "picking flowers and making bouquets for each other"];

export const negativePromptOptions = ["blurry", "low quality", "pixelated", "extra fingers", "deformed hands", "deformed face", "wrong anatomy", "extra people", "nudity", "watermark", "text", "logo", "signature", "out of frame", "cropped", "bad proportions", "malformed limbs", "missing arms", "missing legs", "extra arms", "extra legs", "fused fingers", "too many fingers", "long neck", "duplicate", "morbid", "mutilated", "poorly drawn hands", "poorly drawn face", "mutation", "deformed", "ugly", "bad anatomy", "bad proportions", "extra limbs", "cloned face", "disfigured", "gross proportions", "malformed limbs", "missing arms", "missing legs", "extra arms", "extra legs", "mutated hands", "fused fingers", "too many fingers", "long neck", "cross-eyed", "mutated", "bad body"];

export const maleClothing = ["a comfortable flannel shirt over a white t-shirt", "a classic solid-colored polo shirt", "a cozy cable-knit sweater", "a relaxed long-sleeve linen shirt", "a tailored navy blazer over a crisp white shirt", "a minimalist monochrome hoodie", "a black leather biker jacket", "a lightweight beige trench coat", "a slim-fit button-down shirt with rolled sleeves", "a casual short-sleeve Hawaiian shirt", "a dark denim jacket over a grey t-shirt", "a sleek bomber jacket in olive green", "a formal charcoal suit with slim tie", "a turtleneck sweater in neutral tones", "a varsity jacket with contrast sleeves", "a casual crewneck sweatshirt", "a soft corduroy overshirt in earthy tones", "a lightweight puffer vest over a plaid shirt", "a fitted Henley shirt in muted colors", "a chic mandarin-collar shirt", "a light chambray shirt tucked neatly", "a sharp double-breasted blazer", "a stylish knitted polo shirt", "a clean white oxford shirt", "a modern denim shirt with subtle fading"];
export const malePants = ["khaki-colored chino trousers", "slim-fit dark blue jeans", "casual cargo pants", "tailored grey dress pants", "distressed light blue jeans", "black slim-fit trousers", "olive green jogger pants", "cream linen trousers", "navy tailored chinos", "straight-cut beige khakis", "white summer chinos", "dark corduroy trousers", "pinstriped formal pants", "ankle-length cropped trousers", "faded stone-wash denim jeans", "stretch slim-fit jog jeans", "checked patterned trousers", "classic black dress slacks", "loose-fit carpenter pants", "light grey wool trousers", "camel-colored straight trousers", "slim charcoal chinos", "modern tapered trousers", "high-waist pleated pants", "dark brown relaxed trousers"];
export const femaleClothingOptions = [
    { style: "wearing a simple pashmina hijab", clothing: "a long cotton tunic", bottom: "a pastel-colored pleated skirt" },
    { style: "wearing a Turkish-style square hijab", clothing: "a loose-fitting blouse with cuffed sleeves", bottom: "wide-leg culottes" },
    { style: "with her long, wavy hair down", clothing: "a floral-patterned summer dress", bottom: "" },
    { style: "with a chic bob haircut", clothing: "a white off-the-shoulder top", bottom: "an A-line denim skirt" },
    { style: "with a modern satin hijab wrap", clothing: "a pastel oversized blazer", bottom: "high-waist tailored trousers" },
    { style: "with a sleek ponytail", clothing: "a fitted turtleneck sweater", bottom: "a leather midi skirt" },
    { style: "wearing a chiffon hijab in neutral tones", clothing: "a belted shirt-dress", bottom: "" },
    { style: "with her curly hair styled naturally", clothing: "a crop cardigan", bottom: "wide-leg high-rise jeans" },
    { style: "with a silk scarf tied Parisian-style", clothing: "a striped boatneck blouse", bottom: "straight-leg linen trousers" },
    { style: "with a high bun", clothing: "a ribbed knit top", bottom: "a flared midi skirt" },
    { style: "with a turban-style hijab", clothing: "a belted maxi coat", bottom: "slim-cut tailored pants" },
    { style: "with short pixie hair", clothing: "a sleek sleeveless jumpsuit", bottom: "" },
    { style: "with a messy low bun", clothing: "a lace-trim camisole", bottom: "a pleated maxi skirt" },
    { style: "wearing a monochrome hijab", clothing: "a loose-fit oversized shirt", bottom: "relaxed-fit cargo pants" },
    { style: "with straight medium-length hair", clothing: "a denim jacket", bottom: "a floral sundress" },
    { style: "wearing a printed chiffon hijab", clothing: "a peplum blouse", bottom: "tapered ankle trousers" },
    { style: "with braided hair", clothing: "a sleeveless turtleneck top", bottom: "a high-waist pencil skirt" },
    { style: "with bangs and shoulder-length hair", clothing: "a satin blouse", bottom: "wide-leg palazzo pants" },
    { style: "wearing a neutral-toned hijab", clothing: "a cropped denim jacket", bottom: "a flowy maxi dress" },
    { style: "with soft curls", clothing: "a simple cashmere sweater", bottom: "a plaid pleated skirt" },
    { style: "with sleek long straight hair", clothing: "a wrap blouse", bottom: "fitted cigarette pants" },
    { style: "wearing a pastel georgette hijab", clothing: "a tailored longline vest", bottom: "slim-fit straight trousers" },
    { style: "with a casual ponytail", clothing: "an oversized hoodie", bottom: "biker shorts" },
    { style: "with wavy medium hair", clothing: "a ruffled chiffon top", bottom: "a tiered maxi skirt" },
    { style: "with a soft low bun", clothing: "a lightweight kimono cardigan", bottom: "cropped culotte pants" }
];
export const accessories = ["vintage round-frame glasses", "a cream-colored beret", "a canvas tote bag with typography", "a classic leather-strap watch", "clean white sneakers", "a silk patterned scarf", "oversized square sunglasses", "a slim leather crossbody bag", "chunky white platform sneakers", "a pearl necklace with subtle shine", "a wide-brimmed straw hat", "a minimalist gold bracelet", "a pair of statement hoop earrings", "a structured mini handbag", "a plaid wool scarf", "a pair of Chelsea boots", "a baseball cap with embroidery", "a stylish fedora hat", "a woven rattan handbag", "delicate layered necklaces", "a chic oversized blazer brooch", "sleek ankle boots", "a satin headband", "a vintage pocket watch", "a set of silver stacking rings"];